ERROR_CODES = {
    -1: "TARGET_NOT_FOUND_IN_TOP_100",
    -2: "NETWORK_OR_NAVIGATION_ERROR",
    -3: "BROWSER_OR_PROFILE_ERROR",
    -4: "GOOGLE_CHALLENGE_OR_UNUSUAL_TRAFFIC",
    -5: "INCOMPLETE_IMAGE_RESULTS",
    -6: "RESULT_PARSE_ERROR",
    -7: "INVALID_INPUT",
    -8: "UNEXPECTED_INTERNAL_ERROR",
    -9: "GOOGLE_CONSENT_REQUIRED",
    -10: "SEARCH_PARSE_TIMEOUT",
}

def describe(code: int) -> str:
    if code > 0:
        return "FOUND"
    return ERROR_CODES.get(code, "UNKNOWN_ERROR")
