ERROR_CODES = {
    -1: "TARGET_NOT_FOUND_IN_TOP_100",
    -2: "NAVIGATION_OR_NETWORK_ERROR",
    -3: "BROWSER_LAUNCH_OR_PROFILE_ERROR",
    -4: "GOOGLE_CHALLENGE_OR_UNUSUAL_TRAFFIC",
    -5: "INCOMPLETE_IMAGE_RESULTS",
    -6: "RESULT_PARSE_ERROR",
    -7: "INVALID_INPUT",
    -8: "UNEXPECTED_INTERNAL_ERROR",
}

def describe(code: int) -> str:
    return "FOUND" if code > 0 else ERROR_CODES.get(code, "UNKNOWN_ERROR")
